###Create user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "Username": "astra2",
  "password": "astra",
  "email": ""
}
### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "astra2",
  "password": "astra"
}

> {% client.global.set("auth_token", response.body.AccessToken); %}
### RESEND email confirmation
POST http://localhost:5000/auth/resend_email_confirmation
Content-Type: application/json

{
  "email": ""
}

### SEND Message
POST http://localhost:5000/messages/5
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "hello bro"
}

### GET LATEST
GET http://localhost:5000/messages
Authorization: Bearer {{auth_token}}

### Send message By UserId
POST http://localhost:5000/user/message
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "receiverId": 1,
  "content": "hello new Chat"
}


### UPDATE MESSAGE
PUT http://localhost:5000/message/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content" : "Update Message"
}

### GET Chat
GET localhost:5000/chats/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### DELETE message
DELETE http://localhost:5000/message/4
Authorization: Bearer {{auth_token}}
