// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID        int64
	IsGroup   sql.NullInt64
	Name      sql.NullString
	CreatedAt sql.NullTime
}

type ConversationParticipant struct {
	ID             int64
	UserID         int64
	ConversationID int64
	JoinedAt       sql.NullTime
	IsAdmin        sql.NullInt64
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderID       sql.NullInt64
	Content        string
	SentAt         time.Time
}

type User struct {
	ID                 int64
	Username           sql.NullString
	UsernameNormalized sql.NullString
	PasswordHash       sql.NullString
	Email              sql.NullString
	EmailNormalized    interface{}
	EmailConfirmed     int64
	AvatarPath         sql.NullString
	CreatedAt          time.Time
}
